parameters:
  imageName: 'freeipa-azure-builder:latest'

steps:
- script: |
    set -e
    sudo modprobe {nfs,nfsd}
  displayName: Configure NFS to allow NFS server/client within containers

- task: DownloadPipelineArtifact@0
  displayName: Download prebuilt packages '$(IPA_PACKAGES_ARTIFACT)'
  inputs:
    artifactName: $(IPA_PACKAGES_ARTIFACT)
    targetPath: $(Build.Repository.LocalPath)/dist

- task: DownloadPipelineArtifact@0
  displayName: Download pre-built container '$(IPA_IMAGE_ARTIFACT)'
  inputs:
    artifactName: $(IPA_IMAGE_ARTIFACT)
    targetPath: $(Build.Repository.LocalPath)

- script: |
    set -e
    podman load --input $(Build.Repository.LocalPath)/freeipa-azure-builder-container.tar.gz
    # Work around podman load bug that names loaded image as latest:latest
    podman image tag localhost/latest:latest freeipa-azure-builder:latest ||:
    podman images
    podman inspect freeipa-azure-builder:latest
  displayName: Import pre-built container to the engine
