name: Check PR using Sourcery

on: pull_request

jobs:
  review-with-sourcery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - uses: sourcery-ai/action@438ce67e9f15fbeacb72257da23e2fffb1b6d354
        with:
          token: ${{ secrets.SOURCERY_TOKEN }}
          diff_ref: ${{ github.event.pull_request.base.sha }}
